### ISSUE TITLE
Replace classnames by lit-html/classMap

### ISSUE THREAD

**Issue by Tansito** [carbon-design-system/carbon-custom-elements#218]
We tested that the last PR that @asudoh did about the babel dependencies and ESM modules it worked (really thanks!) but we found that we continue having problems with the `classnames` library now. This library use CJS modules so our proposal is to change this library by the `classMap` imported by the library `lit-html` that you have now as dependency in the project. With this change and taking the `button` component as an example the next code:
```javascript
const classes = classnames(`${prefix}--btn`, {
      [`${prefix}--btn--${kind}`]: kind,
      [`${prefix}--btn--disabled`]: disabled,
      [`${prefix}--btn--icon-only`]: hasIcon && !hasMainContent,
      [`${prefix}--btn--sm`]: small,
      [`${prefix}-ce--btn--has-icon`]: hasIcon,
    });
```
would change to this:
```javascript
const classes = classMap({
          [`${prefix}--btn`]: true,
          [`${prefix}--btn--${kind}`]: kind,
          [`${prefix}--btn--disabled`]: disabled,
          [`${prefix}--btn--icon-only`]: hasIcon && !hasMainContent,
          [`${prefix}--btn--sm`]: small,
          [`${prefix}-ce--btn--has-icon`]: hasIcon
        });
```
For the `button` component at least this worked locally in the fork that I did so if you are agree I can try to make a PR with this change in the different components.

**Comment by Tansito** [comment]
I didn't send any PR yet because I prefer to know your opinion @asudoh about this but If you are agree I can try to have this change as soon as I can (to try to have it for the 0.3.0).

**Comment by asudoh** [comment]
Thanks for your earlier issue and your thoughts here @Tansito - IIRC `classnames` to `classMap` was something I experimented, but didn't make the move for the reason I cannot remember now... Will try to remember why and will get back to you.
