### ISSUE TITLE
Review dependencies

### ISSUE THREAD

**Issue by abdonrd** [carbon-design-system/carbon-custom-elements#224]
In the Readme there is:

```
npm install -S carbon-custom-elements carbon-components lit-html lit-element lodash-es @babel/runtime
```

Why the dependencies are not included? To have an easy install like:

```
npm install carbon-custom-elements
```

**Comment by asudoh** [comment]
Good question - Basically this project took `peerDependencies` route to offer a bit more flexibility in choice of libraries and their versions, but I see your point. Something to mull over as the project goes...
