### ISSUE TITLE
Theme configuration doubt

### ISSUE THREAD

**Issue by Tansito** [carbon-design-system/carbon-custom-elements#227]
With the `carbon-custom-elements` how can I give a theme to a component? For example, how can I setup the `g100` theme to a `modal`? Thanks in advance.

**Comment by asudoh** [comment]
Thank you for asking @Tansito! If you go to https://carbon-custom-elements.netlify.com/?path=/story/modal--default-story and click on Carbon Theme tab at the bottom (or at the right), you can switch to `g100` theme there. If you inspect several colors in modal with Firefox DevTools (Chrome DevTools seems to have a series of style inspection bugs for constructed style sheets), you'll see those colors are defined via CSS custom properties, like `var(--cds-text-01, #161616)` for modal text.

That said, you can theme-switch via CSS custom properties. The one for Storybook is implemented at [here](https://github.com/carbon-design-system/carbon-custom-elements/blob/v0.2.0/.storybook/_container.scss#L13-L27). Probably we should expand the [CSS custom properties doc](https://github.com/carbon-design-system/carbon-custom-elements/blob/a89aa25/docs/styling.md#using-css-custom-properties) for theming.

**Comment by Tansito** [comment]
Solved, thanks @asudoh! The last link worked as a charm.
