### ISSUE TITLE
TypeScript 3.8 breaking change

### ISSUE THREAD

**Issue by Tansito** [carbon-design-system/carbon-custom-elements#328]
With the launch of the TypeScript 3.8 [version](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-rc/) Microsoft introduced a breaking that affects to the carbon-custom-elements. As we can see in the next image:

<img width="1028" alt="Screen Shot 2020-02-27 at 10 20 50 AM" src="https://user-images.githubusercontent.com/9059044/75430247-5a434a00-594b-11ea-8746-cb950b3e32c0.png">

It seems that after 3.8 version the index must contain a strict type and we are using in the `addEventListeners` and `removeEventListeners` (from what I could investigate) a K or K_1 type to index.

**Comment by asudoh** [comment]
Hi @Tansito thank you for reporting - The code is something that is automatically generated by TypeScript toolchain. Tried to upgrade to TypeScript 3.8, but couldn't see a significant change in the (generated) content in `button.d.ts`...

So a couple of questions:

1. If you replace that code in `button.d.ts` with `addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void`, does it work? It's from: https://github.com/microsoft/TypeScript/blob/v3.8.2/lib/lib.dom.d.ts#L6755 where I believe the one in `button.d.ts` came from
2. Do you have a reduced case, or zipped-up version of your project (without confidential stuffs)?

**Comment by Tansito** [comment]
Thank you @asudoh I will start with the first point and I will let you know!

**Comment by Tansito** [comment]
I can confirm that with the first option changing the code from the image with the snippet that you share me @asudoh the error disappeared for the method `addEventListener` in `button.d.ts` :)

**Comment by asudoh** [comment]
Thanks @Tansito - In case you have a zipped-up version of your project (without confidential stuffs) it'll help investigating the issue further.

**Comment by asudoh** [comment]
Another question; What happens if you remove ` | "loadend"` from the first `addEventListener` type definition in [`button.d.ts`](https://unpkg.com/browse/carbon-custom-elements@1.0.0-beta.5/es/components/button/button.d.ts)?
