### ISSUE TITLE
Option to expand the multiselect height

### ISSUE THREAD

**Issue by abdonrd** [carbon-design-system/carbon-custom-elements#385]
There is an option to increase the multiselect height?

<img width="435" alt="Screenshot 2020-05-05 at 21 25 34" src="https://user-images.githubusercontent.com/1007051/81107174-09396e80-8f17-11ea-8b56-604b5a1f4bbb.png">

**Comment by asudoh** [comment]
@abdonrd Thank you for asking - Is it about the launcher button, or is it about the menu body?

**Comment by abdonrd** [comment]
The button no, I mean the list of options.

**Comment by asudoh** [comment]
I see, the design guide doesn't provide different choices of options, though I don't think it stops applications to change that. So I think it's a category of [shadow parts](https://developer.mozilla.org/en-US/docs/Web/CSS/::part).

**Comment by abdonrd** [comment]
Thanks! And there are any polyfill now for the Shadow Parts?

**Comment by asudoh** [comment]
Replicating our conversation offline; According to issue# 252 at webcomponents/polyfills repo it's not the case. Alternate ways are loading an alternate `.css.js` or creating a derived class with additional CSS rules: https://custom-elements.carbondesignsystem.com/?path=/docs/introduction-custom-styles--page
